Implement Big UInt Bitwise Or for modexp
lambdaclass/zksync_era_precompiles pull request #135
Opened 2023-09-25 17:19 UTC by jpcenteno

closes #132

2023-09-25 17:42 UTC, ilitteri requested changes
Looking good! Just some minor details

2023-09-25 17:42 UTC, ilitteri commented on precompiles/Modexp.yul
> +                    mstore(add(resPtr, i), res_i)
We need to add 32 per limb to move to the next memory slot:
```suggestion
                    let offset_i := mul(WORD_SIZE(), i)
                    lhs_i := mload(add(lhsPtr, offset_i))
                    rhs_i := mload(add(rhsPtr, offset_i))
                    res_i := or(lhs_i, rhs_i)
                    mstore(add(resPtr, offset_i), res_i)
```

2023-09-25 17:42 UTC, ilitteri commented on precompiles/Modexp.yul
> +                    res_i := or(lhs_i, rhs_i)
```suggestion
                    let lhs_i := mload(add(lhsPtr, i))
                    let rhs_i := mload(add(rhsPtr, i))
                    let res_i := or(lhs_i, rhs_i)
```

2023-09-26 20:09 UTC, ilitteri commented on precompiles/Modexp.yul
> +                    let ptr_lhs_i := add(rhsPtr, offset_i)
```suggestion
                    let ptr_rhs_i := add(rhsPtr, offset_i)
```

2023-09-26 20:10 UTC, ilitteri requested changes
I think one variable name is wrong.

2023-09-26 21:46 UTC, jpcenteno commented on precompiles/Modexp.yul
> +                    let value_res_i := or(value_lhs_i, value_rhs_i)
TY! I might have broke this when copying and pasting, IDK.

2023-09-27 13:25 UTC, ilitteri approved these changes
LGTM!

## How to test

1. Copy the function and its dependencies into a `Playground.yul` file.
2. Copy the following fallback in the file.
```solidity
// BIG UINT OR TESTS

// 1 Limb
let lhsPtr := 0x00
let rhsPtr := 0x20
let orPtr := 0x40
let nLimbs := 1

// 0000 | 0000 = 0000
mstore(lhsPtr, 0x00)
mstore(rhsPtr, 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0x00

// 1111 | 0000 = 1111
mstore(lhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

// 0000 | 1111 = 1111
mstore(lhsPtr, 0x00)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

// 1111 | 1111 = 1111
mstore(lhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

// 1010 | 0101 = 1111
mstore(lhsPtr, 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
mstore(rhsPtr, 0x5555555555555555555555555555555555555555555555555555555555555555)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

// 0101 | 1010 = 1111 (needed?)
mstore(lhsPtr, 0x5555555555555555555555555555555555555555555555555555555555555555)
mstore(rhsPtr, 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

// 2 Limbs
let lhsPtr := 0x00
let rhsPtr := 0x40
let orPtr := 0x80
let nLimbs := 2

// 0000 0000 | 0000 0000 = 0000 0000
mstore(lhsPtr, 0x00)
mstore(add(lhsPtr, 0x20), 0x00)
mstore(rhsPtr, 0x00)
mstore(add(rhsPtr, 0x20), 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0x00
console_log(mload(add(orPtr, 0x20))) // 0x00

// 1111 1111 | 0000 0000 = 1111 1111
mstore(lhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(lhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0x00)
mstore(add(rhsPtr, 0x20), 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff

// 0000 0000 | 1111 1111 = 1111 1111
mstore(lhsPtr, 0x00)
mstore(add(lhsPtr, 0x20), 0x00)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(rhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff

// 1111 1111 | 1111 1111 = 1111 1111
mstore(lhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(lhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(rhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff

// 1010 1010 | 0101 0101 = 1111 1111
mstore(lhsPtr, 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
mstore(add(lhsPtr, 0x20), 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
mstore(rhsPtr, 0x5555555555555555555555555555555555555555555555555555555555555555)
mstore(add(rhsPtr, 0x20), 0x5555555555555555555555555555555555555555555555555555555555555555)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff

// 0101 0101 | 1010 1010 = 1111 1111 (needed?)
mstore(lhsPtr, 0x5555555555555555555555555555555555555555555555555555555555555555)
mstore(add(lhsPtr, 0x20), 0x5555555555555555555555555555555555555555555555555555555555555555)
mstore(rhsPtr, 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
mstore(add(rhsPtr, 0x20), 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff

// 0000 1111 | 0000 1111 = 0000 1111
mstore(lhsPtr, 0x00)
mstore(add(lhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0x00)
mstore(add(rhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0x00
console_log(mload(add(orPtr, 0x20))) // 0xff

// 1111 0000 | 1111 0000 = 1111 0000
mstore(lhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(lhsPtr, 0x20), 0x00)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(rhsPtr, 0x20), 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0x00

// 0000 1111 | 1111 0000 = 1111 1111
mstore(lhsPtr, 0x00)
mstore(add(lhsPtr, 0x20), 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(rhsPtr, 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
mstore(add(rhsPtr, 0x20), 0x00)
bigUIntBitOr(lhsPtr, rhsPtr, nLimbs, orPtr)
console_log(mload(orPtr)) // 0xff
console_log(mload(add(orPtr, 0x20))) // 0xff
```
3. Run the node.
4. Make the following call to the node:
```shell
zksync-era-cli --host localhost --port 8011 call --contract 0x000000000000000000000000000000000000FFFF --function "" --data 00  --private-key 0x850683b40d4a740aa6e745f889a6fdc8327be76e122f5aba645a5b02d0248db8
```
5. You should see the following output in the node:
```shell
Call SUCCESS
=== Console Logs:
0
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
0
0
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
0
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
0
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
```

2023-09-27 13:34 UTC, merged