fix typos in precompiles/EcPairing.yul
lambdaclass/zksync_era_precompiles pull request #177
Opened 2023-10-27 07:39 UTC by xiaolou86

fix typos in precompiles/EcPairing.yul

2023-10-27 12:10 UTC, ilitteri requested changes
Thanks for the contribution! Just one minor detail and this PR can be merged.

2023-10-27 12:10 UTC, ilitteri commented on precompiles/EcPairing.yul
> +            /// @return xr0, xr1, yr0, yr1, zr0, zr1 The projectiles coordinates of the given G2 point.
This one was just a leftover "s"
```suggestion
            /// @return xr0, xr1, yr0, yr1, zr0, zr1 The projective coordinates of the given G2 point.
```

2023-10-28 01:25 UTC, shuoer86 commented on precompiles/EcPairing.yul
> +            /// @return xr0, xr1, yr0, yr1, zr0, zr1 The projectiles coordinates of the given G2 point.
Thanks for your review. resolved.

2023-10-28 01:25 UTC, shuoer86 commented
@ilitteri Thanks for your review. I have resolved it.

2023-10-28 01:39 UTC, xiaolou86 commented
@ilitteri Thanks for your review. resolved.

2023-11-12 19:03 UTC, closed without merging